### ISSUE TITLE
Build badges are not working for mender jenkins jobs

### ISSUE THREAD

**Issue by olehermanse** [cfengine/cf-bottom#22]
See example: https://github.com/mendersoftware/mender/pull/296

**Comment by olehermanse** [comment]
@oleorhagen PLSFIX

**Comment by oleorhagen** [comment]
We do not have that plugin installed, neither do I think we need it. Maybe mender-bottom should have a static tag?

**Comment by olehermanse** [comment]
If you don't want build badges, I would add a config option, to make it post just the link to the build.

**Comment by olehermanse** [comment]
Mender no longer uses jenkins.
